/**
 * Pi background-wait shim — typebulb's compensation for a capability pi doesn't expose.
 *
 * `typebulb wait` is a wake-up primitive: a process that blocks until an event, then exits, so a
 * harness that re-invokes the agent on a background task's exit turns that exit into a wake
 * (TB-Wait.md). Claude Code has `run_in_background`; **pi has no background
 * bash and no way for an external process to re-invoke the agent** (verified against
 * @earendil-works/pi-coding-agent 0.80.2 — usage.md: "intentionally does not include … background
 * bash"). So on pi a foreground `typebulb wait` would block the very turn whose flush the awaited
 * line depends on — a deadlock.
 *
 * This module ships a tiny pi **extension** that supplies the missing primitive: it intercepts any
 * `typebulb wait …` bash call, blocks the foreground execution (so the turn ends and the embed/turn
 * renders), spawns the real `typebulb wait` in the background itself, and on its exit injects the
 * outcome via `pi.sendUserMessage` — pi's own native "trigger a turn" facility, the analogue of CC's
 * process-exit notification. Because it just runs the real `typebulb wait`, pi inherits all of it for
 * free (the `--match` semantics, the from-0 offset, the 30s cap) and it generalises to BOTH the embed
 * loop and the turn-based bulb loop. The agent-facing instruction stays the one harness-agnostic line.
 *
 * typebulb writes the extension into pi's global extensions dir itself (`ensurePiShim`), gated on pi
 * being present — Claude-Code-only users never get a byte written. pi can't be *told* to load it
 * (no `/reload` typebulb can trigger), so a freshly-placed shim activates on pi's next session start;
 * the one un-activated first session degrades to a benign 30s wait timeout.
 *
 * Lives under `agents/pi/server/` with the rest of the pi adapter — it is pi-specific, even though it's
 * called from the CLI core (`src/index.ts`, `src/commands/agent.ts`), the same src→`agents/pi/server`
 * direction `agentViewer/resolve.ts` already uses for `PiAdapter`. Imported as this bare module, not
 * the pi server barrel, so it pulls in no mirror/createMirror boot.
 */
import { existsSync, mkdirSync, writeFileSync } from 'fs'
import { homedir } from 'os'
import * as path from 'path'

const piHome = () => path.join(homedir(), '.pi', 'agent')
const shimPath = () => path.join(piHome(), 'extensions', 'typebulb-wait.ts')

/**
 * The shim source, written verbatim into pi's extensions dir and loaded by pi (via jiti) inside the
 * pi process — so `node:*` builtins are available and `pi`/`ctx`/`sendUserMessage` are pi's own.
 *
 * `String.raw` so the regex backslashes (`\b`, `\s`) and the `\n` survive into the file literally
 * rather than being processed by this enclosing template. Keep this body free of backticks and `${`.
 * Everything is wrapped so a throw can NEVER break pi's startup — a future pi API change degrades the
 * loop to the optimistic tier (no wake), never "pi won't boot".
 */
export const PI_SHIM_SOURCE = String.raw`// Generated by typebulb — do not edit; overwritten on each run.
import { spawn } from "node:child_process";

function logErr(...a) { try { console.error("[typebulb-wait]", ...a); } catch (e) {} }

// Matches "typebulb wait", "npx typebulb wait", "/path/to/typebulb wait", "pnpm exec typebulb wait", etc.
function isWaitCommand(command) { return /\btypebulb\s+wait\b/.test(String(command || "")); }

export default function (pi) {
  try {
    const pending = new Set();

    pi.on("tool_call", (event, ctx) => {
      try {
        if (!event || event.toolName !== "bash") return undefined;
        const command = event.input && event.input.command;
        if (!isWaitCommand(command)) return undefined;

        // Run the REAL typebulb wait in the background instead of foreground (which would deadlock the
        // turn). It does the mirror/registry lookup, --match and offsets itself. The marker tells it this
        // is a shim-backgrounded (non-blocking) wait, so it runs as a pure subscription: no give-up clock,
        // it waits for the event however long (bounded by the session-shutdown reap below) — an embed's
        // first paint OR a running bulb's next event line alike.
        const child = spawn(command, {
          shell: true,
          stdio: ["ignore", "pipe", "ignore"],
          env: { ...process.env, TYPEBULB_WAIT_SHIM: "1" },
        });
        pending.add(child);
        let out = "";
        if (child.stdout) child.stdout.on("data", (b) => { out += b.toString(); });
        child.on("error", (e) => { pending.delete(child); logErr("spawn", e && e.message); });
        child.on("exit", (code) => {
          pending.delete(child);
          try {
            const text = out.trim();
            // Exit 0 with output is a real outcome (embed ok/error, a turn-based move) -> wake the
            // agent (followUp delivers immediately when idle and queues when streaming — the same call
            // git-merge-and-resolve.ts makes from agent_end). A late wake is fine; it just reports
            // something true. Exit 2/3 (no render yet / server gone) surface passively, no turn.
            if (code === 0 && text) {
              pi.sendUserMessage("typebulb wait result:\n" + text, { deliverAs: "followUp" });
            } else if (ctx.ui && typeof ctx.ui.notify === "function") {
              ctx.ui.notify("typebulb wait: " + (code === 2 ? "timed out, nothing to report" : "ended (code " + code + ")"), "info");
            }
          } catch (e) { logErr("exit", e && e.message); }
        });

        return {
          block: true,
          reason: "Armed in the background. You will be re-invoked automatically with the result when it is ready - do not run this command again; end your turn now and wait for the result.",
        };
      } catch (e) { logErr("tool_call", e && e.message); return undefined; }
    });

    try { pi.on("session_shutdown", () => { for (const c of pending) { try { c.kill(); } catch (e) {} } pending.clear(); }); } catch (e) {}
  } catch (e) { logErr("load", e && e.message); }
}
`

/**
 * Write pi's `typebulb-wait.ts` extension, gated on pi being present — NEVER throws (a best-effort side
 * task on the CLI hot path; a disk/permission error must not crash the user's actual `typebulb` command).
 * No `~/.pi/agent` → the user doesn't use pi → write nothing. Clobbers unconditionally: whatever typebulb
 * you run writes its own shim, so a downgrade lands that version's shim too — no stale file, no versioning.
 */
export function ensurePiShim(): void {
  try {
    if (!existsSync(piHome())) return
    const target = shimPath()
    mkdirSync(path.dirname(target), { recursive: true })
    writeFileSync(target, PI_SHIM_SOURCE)
  } catch {}
}
